language: python

python:
    - "3.6"

services:
    - mysql

install:
    - pip install -r requirements/base.txt

before_script:
    - mysql -e 'create database sterling;'
    - python manage.py migrate

script:
    - python manage.py test