# Generated by Django 2.2.4 on 2019-08-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
