# Generated by Django 2.2.4 on 2019-08-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=20, null=True, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=10, verbose_name='Type'),
        ),
    ]
