# Generated by Django 2.2.8 on 2020-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200412_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='keywords',
            field=models.ManyToManyField(related_name='accounts', to='accounts.Keyword'),
        ),
    ]
