# Generated by Django 2.2.4 on 2019-08-19 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20190819_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50, verbose_name='Transaction Name')),
                ('category', models.CharField(max_length=20, null=True, verbose_name='Category')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('notes', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
            ],
        ),
    ]
