# Generated by Django 2.2.8 on 2020-04-12 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20200412_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, verbose_name='Transaction Name')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=100, null=True, verbose_name='Memo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65, null=True, verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.Transaction')),
            ],
        ),
    ]
