# Generated by Django 2.2.4 on 2019-09-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Transaction Name'),
        ),
    ]
