# Generated by Django 2.2.4 on 2020-01-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190925_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Amount'),
        ),
    ]
