# Generated by Django 2.2.8 on 2020-01-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200111_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('name', 'amount', 'category', 'date')},
        ),
    ]
