# Generated by Django 2.2.8 on 2020-03-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200111_1315'),
        ('transactions', '0006_auto_20200114_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'name', 'amount', 'category', 'date')},
        ),
    ]
