# Generated by Django 2.2.8 on 2020-02-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200207_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[('Asset', 0), ('Liability', 1), ('Income', 2), ('Expense', 3)], default=3, verbose_name='Category Type'),
        ),
    ]
