# Generated by Django 2.2.8 on 2020-03-02 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200111_1315'),
        ('transactions', '0007_auto_20200301_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, verbose_name='Transaction Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65, null=True, verbose_name='Amount')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Category')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('notes', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_transactions', to='accounts.Account')),
            ],
        ),
    ]
